### ISSUE TITLE
Bug Cannot find versions of prisim

### ISSUE THREAD

**Issue by davidbuckleyni** [dansiegel/MauiFest2022#1]
I am guessing here your waiting on your offical nuget feed to play catch up

![image](https://user-images.githubusercontent.com/5619229/172721413-9d2973b6-63b6-4e3b-8187-7f2ac81f02cd.png)

**Comment by dansiegel** [comment]
As noted in the ReadMe

![image](https://user-images.githubusercontent.com/3860573/172725817-3e554ee5-e309-459c-b57e-24261f64dd09.png)
