### ISSUE TITLE
Clicking the physical back button causes the page to return to the SplashPage, not the previous page

### ISSUE THREAD

**Issue by xiguazizi** [dansiegel/MauiFest2022#2]
Running this code, clicking the Android phone's physical back button will cause the page to return to the SplashPage, not the previous pag
![1655996812434](https://user-images.githubusercontent.com/78199747/175332114-35ef29d0-0265-455e-bda4-2a97b038fb63.jpg)
e

**Comment by dansiegel** [comment]
You're not wrong, but can you please open the issue in the Prism.Maui repo

**Comment by xiguazizi** [comment]
> You're not wrong, but can you please open the issue in the Prism.Maui repo

Yes, any test dome built with Prism.Maui has issues with the physical buttons, and there is another issue where the NavigationBar is always noticeably faster than the Navigation Content when each navigation page appears.

**Comment by dansiegel** [comment]
This was a demo app I'm not taking issues for Prism here
